[package]
name = "cargo-toml"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]

[[bin]]
name = "list-cargo-bin"
path = "src/list-cargo-bin.rs"

[dependencies]
serde = "0.9"
serde_derive = "0.9"
toml = "0.3"
